Simple kmod v2
openshift-psap/special-resource-operator-deprecated pull request #35
Opened 2020-10-19 16:02 UTC by zvonkok

Heavy update on the SDK. 

Added lustre-client, simple-kmod, driver-container-base as recipes.
Dependent `SpecialResources` are created now automatically and reconciled. 
New field `imageReference: true` will add RBAC to pull images from other dependent namespaces. 

SRO will deploy from the internal file-system if no `ConfigMap` overrides are generated. 

```
SPECIALRESOURCE=lustre-client make
```

Or if yaml files are updated and should be overriden: 

```
SPECIALRESOURCE=lustre-client make assets
SPECIALRESOURCE=lustre-client make
```

2020-10-19 16:02 UTC, zvonkok commented
@dagrayvid PTAL

2020-10-19 16:37 UTC, ArangoGutierrez requested changes
Looking Good, on a first pass just a few YAML lints and comments on the Dockerfile.
Will be adding more comments as I test this.

2020-10-19 16:37 UTC, ArangoGutierrez commented on Dockerfile
> +FROM golang:1.13 as builder
We could use go 14 or 15, by the time we merge this PR, go 1.5 will be the default on OCP

2020-10-19 16:37 UTC, ArangoGutierrez commented on Dockerfile
> +COPY vendor/ vendor/
We could use a `.dockerignore` file and simply do `COPY . .`

2020-10-19 16:37 UTC, ArangoGutierrez commented on Dockerfile
> +FROM gcr.io/distroless/static:nonroot
this might be a good practice on the upstream side, but for Downstream I would ratter stick with `registry.svc.ci.openshift.org/ocp/4.7:base`

2020-10-19 16:37 UTC, ArangoGutierrez commented on Makefile
> +
```suggestion
```

2020-10-19 16:37 UTC, ArangoGutierrez commented on api/v1beta1/groupversion_info.go
> +
```suggestion
```

2020-10-19 16:37 UTC, ArangoGutierrez commented on api/v1beta1/specialresource_types.go
> +
```suggestion
```

2020-10-19 16:37 UTC, ArangoGutierrez commented on config/crd/bases/sro.openshift.io_specialresources.yaml
> +
```suggestion
```

2020-10-19 16:37 UTC, ArangoGutierrez commented on config/default/kustomization.yaml
> +
```suggestion
```

2020-10-19 16:37 UTC, ArangoGutierrez commented on config/prometheus/monitor.yaml
> +
```suggestion
```

2020-10-19 16:37 UTC, ArangoGutierrez commented on config/rbac/role.yaml
> +
```suggestion
```

2020-10-19 16:37 UTC, ArangoGutierrez commented on config/recipes/driver-container-base/0000-driver-container-base-cr.yaml
> +
```suggestion
```

2020-10-19 16:37 UTC, ArangoGutierrez commented on config/recipes/driver-container-base/manifests/0000-driver-container-base-build.yaml
> +
```suggestion
```

2020-10-19 16:37 UTC, ArangoGutierrez commented on config/recipes/driver-container-base/manifests/0000-driver-container-base-build.yaml
> +
```suggestion
```

2020-10-19 16:37 UTC, ArangoGutierrez commented on config/recipes/driver-container-base/manifests/0000-driver-container-base-build.yaml
> +
```suggestion
```

2020-10-19 16:37 UTC, ArangoGutierrez commented on config/recipes/lustre-client/csi-driver/base/csidriver.yaml
> +
```suggestion
```

2020-10-19 16:37 UTC, ArangoGutierrez commented on config/recipes/lustre-client/csi-driver/base/node.yaml
> +
```suggestion
```

2020-10-19 16:37 UTC, ArangoGutierrez commented on config/recipes/lustre-client/csi-driver/base/rbac.yaml
> +
```suggestion
```

2020-10-19 16:37 UTC, ArangoGutierrez commented on config/recipes/lustre-client/csi-driver/base/rbac.yaml
> +
```suggestion
```

2020-10-19 16:37 UTC, ArangoGutierrez commented on config/recipes/lustre-client/csi-driver/base/rbac.yaml
> +
```suggestion
```

2020-10-19 16:37 UTC, ArangoGutierrez commented on config/recipes/lustre-client/csi-driver/base/rbac.yaml
> +
```suggestion
```

2020-10-19 16:37 UTC, ArangoGutierrez commented on config/recipes/lustre-client/manifests/0000-buildconfig.yaml
> +
```suggestion
```

2020-10-19 16:37 UTC, ArangoGutierrez commented on config/webhook/service.yaml
> +
```suggestion
---
```

2020-10-19 16:37 UTC, ArangoGutierrez commented on config/recipes/simple-kmod/manifests/0000-buildconfig..yaml
> +
```suggestion
```

2020-10-19 16:37 UTC, ArangoGutierrez commented on config/recipes/simple-kmod/0000-simple-kmod-cr.yaml
> +
```suggestion
```

2020-10-19 16:37 UTC, ArangoGutierrez commented on config/recipes/nvidia-gpu/manifests/2000-state-runtime.yaml
> +
```suggestion
```

2020-10-19 16:37 UTC, ArangoGutierrez commented on config/recipes/nvidia-gpu/0000-nvidia-gpu-cr.yaml
> +
```suggestion
```

2020-10-19 16:38 UTC, ArangoGutierrez commented
/unassign @zvonkok 
/assign

2020-10-19 16:44 UTC, zvonkok commented on Dockerfile
> +COPY vendor/ vendor/
This way it is easier, the .dockerignore file would be huge ... I want to make sure that only specific things land in the image, not the other way around.

2020-10-19 16:45 UTC, zvonkok commented on Dockerfile
> +FROM gcr.io/distroless/static:nonroot
Makes sense, but I would go with UBI8 and not 4.7 because this makes it look as it only runs on 4.7. which is not the case.

2020-10-19 16:50 UTC, ArangoGutierrez commented
Also why are we removing `README` and `OWNERS` file ?

2020-10-19 16:53 UTC, zvonkok commented
@ArangoGutierrez ha, good catch, will add them back, that is why it is "Draft".

2020-10-19 16:54 UTC, zvonkok commented
@ArangoGutierrez  There are many reasons why a newline should be at "any" file. One is when files are concatenated, it is always good to have a newline. Some tools cannot interpret the EOF correctly and can fail.

2020-10-19 16:56 UTC, ArangoGutierrez commented
> @ArangoGutierrez There are many reasons why a newline should be at "any" file. One is when files are concatenated, it is always good to have a newline. Some tools cannot interpret the EOF correctly and can fail.

Understood, is an old habit to check for non needed lines when doing code review. but you are totally right.

2020-10-19 16:58 UTC, ArangoGutierrez commented on Dockerfile
> +COPY vendor/ vendor/
`.dockerignore` would look like this
```text
bin/
config/
hack/
README.md
.gitignore
```
Doesn't look that huge to me.

2020-10-19 16:59 UTC, ArangoGutierrez commented
Also remove `bin/manager` , and we probably want to add `bin/` to `.gitignore` to prevent this from getting into future changes

2020-10-19 17:02 UTC, ArangoGutierrez commented on hack/boilerplate.go.txt
> +/*
I am really against calling helper scripts and templates `hack` folder. if this is a template let's call this folder `templates` or something more among those lines. a template to apply a License header is not a hack.

2020-10-19 17:06 UTC, zvonkok commented on hack/boilerplate.go.txt
> +/*
Removed auto-generated folder.

2020-10-19 17:08 UTC, ArangoGutierrez commented
/label tide/merge-method-squash

2020-10-19 17:10 UTC, ArangoGutierrez commented
Let's hold this PR to avoid triggering CI tests until we are good to talk about merging this path
/hold

2020-10-20 18:52 UTC, dagrayvid commented on config/recipes/Makefile
> +	cd config/recipes/$(SPECIALRESOURCE)/manifests && kustomize edit set namespace $(SPECIALRESOURCE)
Replace "kustomize" with $(KUSTOMIZE)

2020-10-21 13:13 UTC, zvonkok commented on config/recipes/Makefile
> +	cd config/recipes/$(SPECIALRESOURCE)/manifests && kustomize edit set namespace $(SPECIALRESOURCE)
Done, thanks.

2020-10-21 13:13 UTC, zvonkok commented on hack/boilerplate.go.txt
> +/*
Done.

2020-10-21 13:15 UTC, zvonkok commented on Dockerfile
> +COPY vendor/ vendor/
To know what exactly goes into the image you would always need to look at the dockerignore file and compare with the file system, too much work. This way one sees exactly what goes in without comparing files and the file system.

2020-10-21 19:19 UTC, ArangoGutierrez commented on config/recipes/nvidia-gpu/manifests/1000-state-driver.yaml
> +          - name: VERSION_ID
https://gitlab.com/nvidia/kubernetes/gpu-operator/-/merge_requests/131
we are now using OPENSHFIT_VERSION env var

2020-10-22 08:46 UTC, zvonkok commented on config/recipes/nvidia-gpu/manifests/1000-state-driver.yaml
> +          - name: VERSION_ID
I am using my own branch of the driver.

2020-10-26 11:19 UTC, zvonkok commented
/unhold

2020-10-26 16:24 UTC, zvonkok commented
/retest

2020-10-26 19:14 UTC, zvonkok commented
/retest

2020-10-26 21:46 UTC, zvonkok commented
/retest

On Mon., Oct. 26, 2020, 22:01 OpenShift Merge Robot <
notifications@github.com> wrote:

> @zvonkok <https://github.com/zvonkok>: The following test *failed*, say
> /retest to rerun all failed tests:
> Test name Commit Details Rerun command
> ci/prow/e2e-aws-upgrade 902e4aa
> <https://github.com/openshift-psap/special-resource-operator/commit/902e4aa060ac28a8137aea3afdfe9d24bdbcf479>
> link
> <https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-psap_special-resource-operator/35/pull-ci-openshift-psap-special-resource-operator-master-e2e-aws-upgrade/1320764808827506688> /test
> e2e-aws-upgrade
>
> Full PR test history
> <https://prow.ci.openshift.org/pr-history?org=openshift-psap&repo=special-resource-operator&pr=35>.
> Your PR dashboard
> <https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:zvonkok>.
>
> Instructions for interacting with me using PR comments are available here
> <https://git.k8s.io/community/contributors/guide/pull-requests.md>. If
> you have questions or suggestions related to my behavior, please file an
> issue against the kubernetes/test-infra
> <https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:>
> repository. I understand the commands that are listed here
> <https://go.k8s.io/bot-commands>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/openshift-psap/special-resource-operator/pull/35#issuecomment-716821221>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA4NPNR4FI6W4GU4QBCLZ73SMXPT7ANCNFSM4SWLCGEQ>
> .
>

2020-10-29 10:04 UTC, zvonkok commented
/bugzilla refresh

2020-10-29 17:25 UTC, dagrayvid commented on config/recipes/lustre-client/0000-lustre-client-cr.yaml
> +        uri: "https://github.com/dagrayvid/driver-containers.git"
We need to remove the reference to my github. This should be completely unnecessary since the Containerfile steps which are used are in config/recipes/lustre-client/manifests/0000-buildconfig.yaml. If I recall correctly this was added only because the git field is required. We could also create an openshift-psap/lustre-client-driver repo if we want, and add a RHEL7 and RHEL8 Containerfile instead.

2020-11-03 20:19 UTC, ArangoGutierrez requested changes

2020-11-03 20:19 UTC, ArangoGutierrez commented on Makefile
> +VERSION ?= 0.0.1
on NFD we are using `vX.Y.Z` maybe we can do the same here prefix a v here

2020-11-03 20:19 UTC, ArangoGutierrez commented on config/recipes/nvidia-gpu/0000-nvidia-gpu-cr.yaml
> +        uri: "https://gitlab.com/zvonkok/driver.git"
We should use openshift-psap gitlab

2020-11-03 20:19 UTC, ArangoGutierrez commented on Makefile
> +	@echo "##################### TODO UNIT TEST"
```suggestion
	@echo "##################### TODO UNIT TEST #####################"
```

2020-11-03 20:19 UTC, ArangoGutierrez commented on config/recipes/driver-container-base/manifests/0000-driver-container-base-build.yaml
> +    yum config-manager --set-enabled rhocp-{{.ClusterVersionMajorMinor}}-for-rhel-8-x86_64-rpms || true
Could we use `dnf` instead?

2020-11-03 20:19 UTC, ArangoGutierrez commented on config/recipes/driver-container-base/manifests/0000-driver-container-base-build.yaml
> +    yum -y --releasever={{.OperatingSystemDecimal}} --setopt=install_weak_deps=False --best install $KERNEL_CORE
same here, `dnf` works perfectly on UBI images so is ok to use

2020-11-03 20:19 UTC, ArangoGutierrez commented on config/recipes/lustre-client/0000-lustre-client-cr.yaml
> +        uri: "https://github.com/dagrayvid/driver-containers.git"
Agree++ please move it to a openshift-psap based repo.

2020-11-04 09:37 UTC, zvonkok commented on config/recipes/nvidia-gpu/0000-nvidia-gpu-cr.yaml
> +        uri: "https://gitlab.com/zvonkok/driver.git"
Why gitlab?

2020-11-04 09:38 UTC, zvonkok commented on config/recipes/driver-container-base/manifests/0000-driver-container-base-build.yaml
> +    yum config-manager --set-enabled rhocp-{{.ClusterVersionMajorMinor}}-for-rhel-8-x86_64-rpms || true
We may also need support for RHEL7, leaving yum.

2020-11-04 09:38 UTC, zvonkok commented on config/recipes/driver-container-base/manifests/0000-driver-container-base-build.yaml
> +    yum -y --releasever={{.OperatingSystemDecimal}} --setopt=install_weak_deps=False --best install $KERNEL_CORE
RHEL7 see above

2020-11-04 15:23 UTC, dagrayvid commented on config/recipes/lustre-client/0000-lustre-client-cr.yaml
> +        uri: "https://github.com/dagrayvid/driver-containers.git"
@zvonkok Just to clarify before I do this... Is the git field required in the CR?

2020-11-05 11:39 UTC, zvonkok commented on Makefile
> +VERSION ?= 0.0.1
Done.

2020-11-05 11:40 UTC, zvonkok commented on config/recipes/lustre-client/0000-lustre-client-cr.yaml
> +        uri: "https://github.com/dagrayvid/driver-containers.git"
I made it optional. I just left the buildArgs as a reference, but those can also be removed.

2020-11-09 20:16 UTC, dagrayvid commented on config/recipes/lustre-client/manifests/0000-buildconfig.yaml
> +    type: Git
Need to delete this now that we deleted the git uri from the special resource.

```suggestion
```

2020-11-12 13:33 UTC, zvonkok commented
We need to get this merged to move forward with SRO and the enablement in 4.7 and z-stream 4.6

2020-11-16 20:40 UTC, dagrayvid commented on api/v1beta1/specialresource_types.go
> +type SpecialResourceBuilArgs struct {
Fix typo, 

```suggestion
// SpecialResourceBuildArgs defines the observed state of SpecialResource
type SpecialResourceBuildArgs struct {
```

It would also be good if the comments in this file were a bit more descriptive.

2020-11-16 20:41 UTC, dagrayvid commented on api/v1beta1/specialresource_types.go
> +	BuildArgs []SpecialResourceBuilArgs `json:"buildArgs,omitempty"`
```suggestion
	BuildArgs []SpecialResourceBuildArgs `json:"buildArgs,omitempty"`
```

2020-11-17 11:11 UTC, zvonkok commented
/retest

2020-11-20 02:42 UTC, ArangoGutierrez requested changes

2020-11-20 02:42 UTC, ArangoGutierrez commented on Makefile
> +generate: controller-gen
Not needed, this is a nice tool when bootstrapping from the operatorFramework SDK , also the hack folder and it's content was removed, so we better also rm this make rule

2020-11-20 02:42 UTC, ArangoGutierrez commented on Makefile
> +podman-build: test
for all the PSAP operators we use `local-image`

2020-11-20 02:42 UTC, ArangoGutierrez commented on Makefile
> +podman-push:
for all the PSAP operators we use `local-image-push`
I know this is part of the SDK 1.0.0++ , but we should have a standard across our maintained operators, we can have both make rules if desired.

2020-11-20 02:42 UTC, ArangoGutierrez commented on go.mod
> +go 1.13
can we do at least  1.14? , 13 is very old, if we wanna target this for 4.7 (which uses 1.15) , we might be at least 1 version off

2020-11-20 02:42 UTC, ArangoGutierrez commented on config/crd/patches/webhook_in_specialresources.yaml
> +apiVersion: apiextensions.k8s.io/v1beta1
From Kubernetes Docs

> Make sure your Kubernetes cluster has a master version of 1.16.0 or higher to use apiextensions.k8s.io/v1

the beta1 is pre 1.16, and according to the `go.mod` file we are now using 1.19

Ref: [apiextensions](https://v1-17.docs.kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#before-you-begin)

2020-11-20 02:42 UTC, ArangoGutierrez commented on config/crd/patches/cainjection_in_specialresources.yaml
> +apiVersion: apiextensions.k8s.io/v1beta1
From Kubernetes Docs

> Make sure your Kubernetes cluster has a master version of 1.16.0 or higher to use apiextensions.k8s.io/v1

the beta1 is pre 1.16, and according to the `go.mod` file we are now using 1.19

Ref: [apiextensions](https://v1-17.docs.kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#before-you-begin)

2020-11-20 02:42 UTC, ArangoGutierrez commented on config/crd/bases/sro.openshift.io_specialresources.yaml
> +apiVersion: apiextensions.k8s.io/v1beta1
From Kubernetes Docs

> Make sure your Kubernetes cluster has a master version of 1.16.0 or higher to use apiextensions.k8s.io/v1

the beta1 is pre 1.16, and according to the `go.mod` file we are now using 1.19

Ref: [apiextensions](https://v1-17.docs.kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#before-you-begin)

2020-11-20 02:42 UTC, ArangoGutierrez commented on api/v1beta1/groupversion_info.go
> +package v1beta1
Left a comment on the CustomResourceDefiniton  about using V1 given that we are targeting for Kube 1.19

2020-11-20 10:43 UTC, zvonkok commented on Makefile
> +generate: controller-gen
Please have a look at what controller-gen is doing: https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/reference/controller-gen.md (hint RBAC, CRD generation by the presence of special marker comments)

2020-11-20 10:56 UTC, zvonkok commented on api/v1beta1/groupversion_info.go
> +package v1beta1
How is the mature level of SROs API related to kube 1.19?

2020-11-20 11:03 UTC, zvonkok commented on config/crd/patches/cainjection_in_specialresources.yaml
> +apiVersion: apiextensions.k8s.io/v1beta1
There are two items that need to match, the client version against the server version, saying that the client is running 1.19 does not mean that the API server understands it. A client with the newest APIs does not guarantee that the server understands it. Anyway in this case 4.6 and 4.7 have the apiextensions/v1 API. This has nothing todo with the client version and what the API server supports.

2020-11-20 11:07 UTC, zvonkok commented on go.mod
> +go 1.13
We are targeting for 4.6 and 4.7

2020-11-20 11:29 UTC, ArangoGutierrez commented on go.mod
> +go 1.13
4.6 is also Go 1.15

2020-11-20 11:32 UTC, ArangoGutierrez commented on Makefile
> +generate: controller-gen
OK, the to my point ,
```
 	$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="./..."
```

let's remove the `object:headerFile="hack/boilerplate.go.txt" ` piece of that line so it won't complain bc the file doesn't exists

2020-11-20 11:35 UTC, zvonkok commented on go.mod
> +go 1.13
This directive has nothing todo with the current go version used for building. It has a different semantic meaning. I am building with 1.15. This just implies which minimum version needs here to build the software.

2020-11-20 11:41 UTC, ArangoGutierrez commented on go.mod
> +go 1.13
I know that's why I say moving it to 1.14, you have all the deps updated and that's awesome, but given that this is now the "upstream" version of SRO, we don't want to confuse users that might think they can build with go 1.13 (even if they can today, some weird change might appear tomorrow)

2020-11-20 12:22 UTC, ArangoGutierrez commented
/priority critical-urgent

2020-11-20 13:00 UTC, zvonkok commented
/retest

2020-11-24 15:18 UTC, ArangoGutierrez commented
/test e2e-aws

2020-11-24 17:22 UTC, ArangoGutierrez commented
/test e2e-aws

2020-11-24 19:36 UTC, ArangoGutierrez commented
/retest

2020-11-24 20:59 UTC, zvonkok commented on Makefile
> +generate: controller-gen
Lets keep this, this might come handy later to add some thin/marker for the generated files by the sdk. We will address this the next time.

2020-11-24 21:05 UTC, zvonkok commented
@ArangoGutierrez the update to go 1.14 in go mod triggered a go mod vendor so some changes in the vendor folder as well.

2020-11-24 22:59 UTC, ArangoGutierrez approved these changes
Thanks @zvonkok , this is a major effort 
/lgtm

2020-11-24 23:01 UTC, merged