Add CVO manifests
openshift-psap/special-resource-operator-deprecated pull request #42
Opened 2020-12-02 19:39 UTC by zvonkok

This PR labels the Dockefile for CVO inclusion.
Adds auto-generation of CVO manifests and adds image-references and ClusterOperator CR.

2020-12-02 20:04 UTC, ArangoGutierrez requested changes
just a nit, could you rename the files to a more descriptive name , all files are  
 cvo-manifests/0001_specialresource_cvo_manifest.yaml  0001 to 0011....
better to have 00XX_specialresource_KUBERNETESOBJECT.yaml
example
0001_specialresource_CustomResourceDefinition.yaml

2020-12-02 20:04 UTC, ArangoGutierrez commented on Dockerfile
> +FROM registry.svc.ci.openshift.org/ocp/builder:rhel-8-golang-1.15-openshift-4.7 AS builder
we can leave golang here, what really matters is to make this change in the downstream version

2020-12-02 20:04 UTC, ArangoGutierrez commented on Dockerfile
> +FROM registry.svc.ci.openshift.org/ocp/4.7:base
same

2020-12-02 20:20 UTC, dagrayvid commented
> just a nit, could you rename the files to a more descriptive name , all files are
> cvo-manifests/0001_specialresource_cvo_manifest.yaml 0001 to 0011....

Can we rename `cvo-manifests` to just `manifests`, to match other CVO managed operators?

2020-12-02 20:35 UTC, dagrayvid commented on Makefile
> +csplit:
Is this empty make target intentional?

2020-12-02 20:41 UTC, ArangoGutierrez approved these changes
/lgtm

2020-12-02 20:48 UTC, ArangoGutierrez approved these changes
/lgtm

2020-12-02 21:06 UTC, dagrayvid commented
Thanks for the fixes.
/lgtm

2020-12-02 21:07 UTC, dagrayvid approved these changes

2020-12-03 00:21 UTC, dagrayvid commented
/retest

2020-12-03 01:29 UTC, dagrayvid commented
/retest

2020-12-03 05:23 UTC, zvonkok commented
/retest

On Thu., Dec. 3, 2020, 04:26 OpenShift Merge Robot <notifications@github.com>
wrote:

> @zvonkok <https://github.com/zvonkok>: The following tests *failed*, say
> /retest to rerun all failed tests:
> Test name Commit Details Rerun command
> ci/prow/e2e-aws-upgrade 859e0d4
> <https://github.com/openshift-psap/special-resource-operator/commit/859e0d48e0ccd2518db2c588ad6f30247e2355bc>
> link
> <https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-psap_special-resource-operator/42/pull-ci-openshift-psap-special-resource-operator-master-e2e-aws-upgrade/1334308755721949184> /test
> e2e-aws-upgrade
> ci/prow/e2e-aws 859e0d4
> <https://github.com/openshift-psap/special-resource-operator/commit/859e0d48e0ccd2518db2c588ad6f30247e2355bc>
> link
> <https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-psap_special-resource-operator/42/pull-ci-openshift-psap-special-resource-operator-master-e2e-aws/1334291627996352512> /test
> e2e-aws
>
> Full PR test history
> <https://prow.ci.openshift.org/pr-history?org=openshift-psap&repo=special-resource-operator&pr=42>.
> Your PR dashboard
> <https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:zvonkok>.
>
> Instructions for interacting with me using PR comments are available here
> <https://git.k8s.io/community/contributors/guide/pull-requests.md>. If
> you have questions or suggestions related to my behavior, please file an
> issue against the kubernetes/test-infra
> <https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:>
> repository. I understand the commands that are listed here
> <https://go.k8s.io/bot-commands>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/openshift-psap/special-resource-operator/pull/42#issuecomment-737641162>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA4NPNWG57FABO3KXIUP3PDSS4AM5ANCNFSM4UK6P5IA>
> .
>

2020-12-03 22:15 UTC, ArangoGutierrez commented
/retest

2020-12-03 22:33 UTC, dagrayvid commented
/retest

2020-12-04 00:33 UTC, ArangoGutierrez commented
/retest

2020-12-04 02:02 UTC, dagrayvid commented
/retest

2020-12-10 10:36 UTC, closed without merging